spring:
  application:
    name: oj-backend-file-service
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/oj
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 3
    host: redis
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 注册到 nacos 服务
  cloud:
    nacos:
      server-addr: nacos:8848
server:
  address: 0.0.0.0
  port: 8108
  servlet:
    context-path: /api/file
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
# 开启knife4j接口文档
knife4j:
  enable: true
# 对象存储
cos:
  client:
    accessKey: AKIDraMe1N3ri1bHvjgXUSKKWmBgK9tm2Ng5
    secretKey: eRKDEKb3gKBeAlZRTbgekllhf1OmWPLR
    region: ap-chengdu
    bucket: blog-1312417182